version: "3"

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 127.0.0.1:27017:27017

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 127.0.0.1:8081:8081
